apiVersion: v1
kind: Secret
metadata:
  name: akri-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: akri
  url: https://project-akri.github.io/akri/