apiVersion: v1
kind: Secret
metadata:
  name: argoproj-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: argoproj
  url: https://argoproj.github.io/argo-helm/