apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: infra
  source:
    repoURL: 'https://github.com/gerwinjansen/home-automation-infra.git'
    path: argocd
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - ingress-values.yaml
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true