apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: infra
  source:
    repoURL: 'https://github.com/gerwinjansen/home-automation-infra.git'
    path: home-assistant
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: home-assistant
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true