apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-app-of-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: infra
  source:
    repoURL: 'https://github.com/gerwinjansen/home-automation-infra.git'
    targetRevision: task/add-otel-collector
    path: infra-apps
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true