apiVersion: v2
name: argocd
type: application
version: 0.0.0
appVersion: "0.0.0"
dependencies:
  - name: argo-cd
    alias: argocd
    version: 9.0.3
    repository: https://argoproj.github.io/argo-helm