apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: akri-dsmr-p1-to-usb
spec:
  capacity: 1
  discoveryHandler:
    name: udev
    discoveryDetails: |
      groupRecursive: true
      udevRules:
      - ATTRS{manufacturer}=="FTDI", ATTRS{product}=="FT232R USB UART"