name: Validate charts and manifests

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
  workflow_dispatch:

env:
  CRDS-CATALOG: https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json

jobs:
  validate-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.1
        with:
          version: v3.19.0

      - name: Install Kubeconform plugin
        run: |
          helm plugin install https://github.com/jtyr/kubeconform-helm

      - name: Run Kubeconform plugin
        run: |
          helm kubeconform argocd/
          helm kubeconform cert-manager/

  validate-argocd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Run Kubeconform
        uses: docker://ghcr.io/yannh/kubeconform:latest
        with:
          entrypoint: '/kubeconform'
          args: "-strict -summary -schema-location default -schema-location ${{ env.CRDS-CATALOG }} infra-apps/"